sudo: required
language: node_js
notifications:
    email: matheusmayron8@gmail.com
node_js:
- 11.15.0
services:
- postgresql
env:
    global:
    - NODE_ENV: test
    -TRAVIS: true
addons:
    postgresql: '9.3'
before_script:
- psql -c 'create database ts_api_test;' -U postgres
- nom i -g sequelize-cli gulp-cli
- cd server/
- sequelize db:migrate --env test
- npm install
- gulp
scripts:
- npm run unit-test
- npm run integration-test